name: example
description: an example app for `yakforward_logo`
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  yakforward_logo: 
    git:
      url: https://github.com/yakforward-ou/yakforward_logo.git
      ref: main
      
dev_dependencies:
  flutter_lints: ^2.0.2
