name: yakforward_logo
description: Logo for `yakforward` brand
publish_to: 'none'
version: 1.0.1
homepage: https://www.yakforward.com

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  fonts:
    - family: yakforward
      fonts:
        - asset: fonts/yakforward-logo.ttf
