name: yakforward_logo
description: Logo for `yakforward` brand
version: 1.0.0
homepage: https://www.yakforward.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: yakforward
      fonts:
        - asset: fonts/yakforward-logo.ttf
